### ISSUE TITLE
Problem with date format (mm/dd/yy)

### ISSUE THREAD

**Issue by DodoLeDev** [FilenCloudDienste/filen-mobile#101]
As an European user, the date format under the file name _can't be more disturbing than now!_ 😅

Actually, the date follows this syntax: `mm/dd/yy`, **but its not the only one used around the world!**  
In France, we use the format `dd/mm/yy`, and in some British countries it's `yy/mm/dd`!

Could you please change the date format depending on the language set or just add a setting to customize it?

**Comment by DanielProg39** [comment]
Yes, I'd also add that in Ukraine and in most countries of Eastern Europe and post-USSR we use `dd.mm.yy` format

**Comment by roaldarbol** [comment]
Just as an addition, the ISO standard is `yyyy-mm-dd` (https://en.wikipedia.org/wiki/ISO_8601). I think this is also the easiest way of sorting/locating files. :-)

**Comment by jnolan7599** [comment]
I'll add another vote for @roaldarbol 's suggestion. Once you go ISO 8601 & metric, you don't go back. ;-)
