### ISSUE TITLE
Enable preview of .heic image files in filen android app

### ISSUE THREAD

**Issue by Dev22222222** [FilenCloudDienste/filen-mobile#110]
Unable to preview the photos taken in iphone which are having .heic extension in android app. It is visible in ios app. It will be good to enable the same in android app.

**Comment by Dwynr** [comment]
Working on it for a future release.

**Comment by Mangoes** [comment]
After 1 year asking and waiting for this, still nothing in version 2.0.20.

All major Android phones (Samsung, etc...) have been using heic for several years now. Nobody uses jpeg anymore, other than people with very old phones.

Mega has supported heic on Android for years, and it is open source. Others as well.

What is taking Filen so Long ? Please hurry. Thanks.

**Comment by Dwynr** [comment]
Experimental support for HEIC on android will be added in the next update. Should work for Android 10+ with HEIC format support.
