### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by trymeouteh** [FilenCloudDienste/filen-mobile#113]
Please have the option to support multiple accounts in Filen. This will allow users to sync files on their device to their personal and work accounts.

**Comment by EdwardLangdon** [comment]
I think this could be solved by sharing the file or folder with the accounts using Share ?

**Comment by DanielProg39** [comment]
> Please have the option to support multiple accounts in Filen. This will allow users to sync files on their device to their personal and work accounts.

Just note that you allowed to have only one free account
