### ISSUE TITLE
Error "upload chunks are not matching"

### ISSUE THREAD

**Issue by crophit** [FilenCloudDienste/filen-mobile#114]
Sometimes when uploading some files I get the error message "upload chunks are not matching" and the file is not uploaded to the cloud drive. I start the same upload again and everything works as expected. In a case where there are many files marked for upload, I can't see which file was not uploaded. There is no option to try again. And in the error message, I can't see the filename of the file that failed to upload.

**Comment by Dwynr** [comment]
Should be fixed in the latest version available right now (2.0.27). LMK if the issue persists.
