### ISSUE TITLE
"Choose a folder" dialog overlaps with bottom folder

### ISSUE THREAD

**Issue by nopil3os** [FilenCloudDienste/filen-mobile#116]
When in List view and moving things around, the "Choose a folder" dialog overlaps with the folder at the bottom of the list and it is impossible to choose that folder:

![image](https://user-images.githubusercontent.com/2642986/198550057-279d2b6b-b6d1-4d99-ba05-8921882d268c.png)

Both on Android (Pixel 6a, Android 13) and iOS (iPhone 13, iOS 16.1)

**Comment by Dwynr** [comment]
Will fix this in the next release. Best way to handle this is probably to hide the dialog when the list is scrolled all the way to the bottom.
