### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by eloffmarijan** [FilenCloudDienste/filen-mobile#117]
I can't upload files like apks, documents and zips. Showing error popups message. But I can upload images and audios without any problem. Please fix..
I will add the images of that below.
![Screenshot_20221029-212343_Filen](https://user-images.githubusercontent.com/101601874/198841056-34c45cd3-dcf6-4194-bad8-3e0800adc65a.png)
![Screenshot_20221029-212325_Filen](https://user-images.githubusercontent.com/101601874/198841065-621791f4-2dad-4e51-8054-307f906df2ac.png)
![Screenshot_20221029-211749_Filen](https://user-images.githubusercontent.com/101601874/198841066-a01944bd-dc00-4d24-8354-68782d4fbc65.png)

**Comment by Dwynr** [comment]
Thanks for reporting. 

Fixed: https://github.com/FilenCloudDienste/filen-mobile/commit/c7da62e658fb626b1f06ede7364d609e31136a1a

Will be included in the next update.
