### ISSUE TITLE
Issues when uploading many files

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#119]
When I tried to upload many small (3MB on average) files, I saw this:
![IMG_20221104_144548.jpg](https://user-images.githubusercontent.com/63293432/199976624-0a743328-b59c-4593-aeef-4e22baa9072c.jpg)
And this:
![IMG_20221104_144452.jpg](https://user-images.githubusercontent.com/63293432/199976682-2931bf7d-31a8-491c-9b89-f85f26f083a7.jpg)
As a result, 6 files weren't uploaded

**Comment by Dwynr** [comment]
Should be fixed in the latest version available right now (2.0.27). LMK if the issue persists.

**Comment by DanielProg39** [comment]
> Should be fixed in the latest version available right now (2.0.27). LMK if the issue persists.

NP, will test that soon

**Comment by DanielProg39** [comment]
> Should be fixed in the latest version available right now (2.0.27). LMK if the issue persists.

Well, I deleted and uploaded the same files again and didn't have a single issue.
But I had another one: I deleted a folder with files, than in trash I selected it and pressed "Delete permanently", after that I created the same folder and uploaded the same files to it. Then I suddenly realized that in storage counter changed (I deleted and uploaded the same files, so theoretically they take the same amount of space) as if I had these files twice, I mean if I didn't delete them, but just uploaded them again. I fixed this by putting a random file to trash and using "Empty trash" option. All of this I did in mobile app, so take a look. Btw, the web app displayed the same amount of used storage as in the app all the time.

**Comment by DanielProg39** [comment]
> storage counter changed as if I had these files twice, I mean if I didn't delete them, but just uploaded them again.

@Dwynr Have you fixed that? Don't want to disturb you, just want to make sure that I can delete files separately again.

P.S. Btw, check the Filen Drive pull requests: I translated it into russian and Ukrainian

**Comment by Dwynr** [comment]
> > storage counter changed as if I had these files twice, I mean if I didn't delete them, but just uploaded them again.
> 
> @Dwynr Have you fixed that? Don't want to disturb you, just want to make sure that I can delete files separately again.
> 
> P.S. Btw, check the Filen Drive pull requests: I translated it into russian and Ukrainian

Hi Daniel,

I will take a look at the issue as soon as possible. Next release in our development cycle will be the mobile app. If I forget for some reason just ping me again.

Will also merge your PR on the web drive asap.

**Comment by DanielProg39** [comment]
> If I forget for some reason just ping me again.

@Dwynr I saw you are working on a mobile app, just a reminder

**Comment by DanielProg39** [comment]
> storage counter changed as if I had these files twice, I mean if I didn't delete them, but just uploaded them again.

@Dwynr Have you fixed that? Sorry for spamming on this issue
