### ISSUE TITLE
[Feature request] Two-way synchronization for select folders

### ISSUE THREAD

**Issue by AbstractGeek** [FilenCloudDienste/filen-mobile#12]
It will be nice to have the ability to sync select folders in mobile apps (akin to what Dropsync and others provide). 

Thanks for developing filen!

**Comment by dermitdemdino** [comment]
Why is it not possible to select folders for synchronization? For example the pictures ("DCIM") folder, but also others. Shouldn't this be an elementary function of this app?

**Comment by nep2ner** [comment]
Love the new DCIM syncing feature! Being able to specify other folders to sync in a similar way would be really nice to use also.

**Comment by trymeouteh** [comment]
Would like to  have two way syncing on Android with multiple folders and have this feature run in the background without the app being open.

**Comment by jnolan7599** [comment]
@DanielProg39 [Agreed](https://github.com/FilenCloudDienste/filen-mobile/issues/38#issuecomment-1365664487)... I raised a simlar though with #143 .

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
