### ISSUE TITLE
iOS -- "Save Page" makes the app crash

### ISSUE THREAD

**Issue by Hekel1989** [FilenCloudDienste/filen-mobile#121]
Morning,
Yesterday I was trying to use the "Save Page" feature on IOS on the iPad, and Filen crashed, repeatedly, every time.

The steps are reproducible and they are:
1. Long press on any page where the "Save Page" would appear (eBook reader, Comics reader, etc.)
2. Click on the 3 dots to select the Filen app.
3. The app will hang for a moment, and return to the previous "Save Page" tab.

This feature works with similar providers (MEGA for example), so it seems to be a bug.

OS: iOS 15.6.1
HW: IPad Pro 11 Inch

I will try again after upgrading to iOS 16 and update if necessary.

**Comment by Dwynr** [comment]
Is it only crashing with certain files or with every file type? Can you try sharing a simple image into the app?

**Comment by Hekel1989** [comment]
> Is it only crashing with certain files or with every file type? Can you try sharing a simple image into the app?

My test is with JPG and PNG.
The Share feature works, what seems to crash it is the "Save Page" iOS dialog box (apologies, I don't know how iOS calls it).

If I use the "Share" feature, it works.

Please find below a screenshot of the button that makes it crash 

![425F4397-6D5A-4474-84AB-4DD6EFD79FC7.jpg](https://user-images.githubusercontent.com/28776601/201316548-01bb2b26-96a8-432e-8724-f56a4ad7a884.jpg)

**Comment by Dwynr** [comment]
Ah alright got you, I know what you mean now. Let me reproduce it and look for a fix.

**Comment by Hekel1989** [comment]
> Ah alright got you, I know what you mean now. Let me reproduce it and look for a fix.

If you need me more info or you'd like me to test something, please let me know :)
