### ISSUE TITLE
Incorrect folder size

### ISSUE THREAD

**Issue by kou-kee** [FilenCloudDienste/filen-mobile#122]
When I create a folder A among other folders and open the parent folder of the folder A on a different device, the folder shows wrong size (confirmed on the official app on iPadOS)
In the picture, 2 folders has same value but the first one is actually 0 bytes since it is a newly created folder on other device. Restarting the app temporarily fixes this bug.
![C528CADE-E1B7-4189-9AA1-DC656F9F8C1E](https://user-images.githubusercontent.com/98938086/201277504-e071a72f-c4bb-44fd-be20-4ddef7ddf87a.jpeg)

**Comment by Dwynr** [comment]
Fixed in the upcoming update.

**Comment by kou-kee** [comment]
Thank you!
