### ISSUE TITLE
Error when using a vpn together

### ISSUE THREAD

**Issue by LeslyeCream** [FilenCloudDienste/filen-mobile#128]
Currently I can't get filen to detect an internet connection if I use a vpn. The effect is immediate; I disable vpn the "device is offline" disappears. The same result on three different vpn /wi-fi /devices. 

The connection is partial in any case (I can log in and browse folders but nothing else).

**Comment by Dwynr** [comment]
Should probably debug that with your VPN provider since it works as soon as you turn it off.
