### ISSUE TITLE
Issues with the ui 

### ISSUE THREAD

**Issue by Moon-Mind** [FilenCloudDienste/filen-mobile#130]
After you make the image view  size smaler the select Option gone
![Screenshot_20221127-225830.png](https://user-images.githubusercontent.com/52799853/204161864-d0c9b405-7d8c-4918-9fdb-85ddf45d1579.png)

Also in splitscreeen the app show the image like normal size and dont scaling with the window size 
![Screenshot_20221127-225514.png](https://user-images.githubusercontent.com/52799853/204161706-9b5469c8-b38e-49bf-87b1-ce0744c19bc2.png)
![Screenshot_20221127-225612.png](https://user-images.githubusercontent.com/52799853/204161769-55cf6dc4-ffbe-4b99-8f41-43f2a5ac963b.png)

**Comment by Dwynr** [comment]
The selection indicator is automatically removed once the thumbnail are too small to prevent overlapping.

The scaling issue should be fixed in the next update.
