### ISSUE TITLE
[Feature Request] Third party access

### ISSUE THREAD

**Issue by ahmuro** [FilenCloudDienste/filen-mobile#132]
This is an issue not specifically about the mobile app, but as the service as a whole.

Right now, the only thing preventing me from fully ditching Gdrive and use Filen as my main cloud, is the lack of access to third party apps.
Specifically, I use [FolderSync](https://www.tacit.dk/foldersync) on Android to sync stuff from my phone directly to Gdrive, that then is synced to my pc for backup or sync to other services. This arrangement works for me because it allows me to have all my stuff backed up immediately while I'm away, instead of waiting until I am at home to sync trough Syncthing for example.

I contacted the FolderSync dev and the response was:

>Unfortunately they do not support 3rd party access so support is not possible until that change.

Understandably, this may be a complex issue because of the encryption and other implementations needed, but I really believe that this could be an important boost for functionality, since the ability to connect with another service or app is a feature of wide use in many others services.

Thanks.

**Comment by jnolan7599** [comment]
Another Syncthing & FolderSync user reporting in. I echo @ahmuro request.

**Comment by ahmuro** [comment]
A feature that could solve or mitigate this would be android folder sync feature. Just like FolderSync or the desktop Filen app, having a service running monitoring a predefined folder that worked like the sync pairs in desktop, so we could create and select a local folder to link with a cloud folder and this automatically synced the changes.
This would require fewer adaptations for the API and wouldn't compromise security nor encryption.

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
