### ISSUE TITLE
Text still cropped in english.

### ISSUE THREAD

**Issue by ahmuro** [FilenCloudDienste/filen-mobile#133]
2.0.21 included a fix for the length of text in certain translations. However, I'm on english 2.0.31 and the app text still appears cropped for the last word of every string of the app. The text of the files and folders is shown correctly.

Currently, using android 12, not vanilla but almost. First releases of version 2 of the app showed all the text properly, not sure which one started with this issue.

Thanks

![Screenshot_20221128-174216_Filen](https://user-images.githubusercontent.com/62005324/204404984-842a7d64-3d97-4d50-a3bd-d28064e04422.png)

**Comment by DanielProg39** [comment]
I think that it depends on what font size is set in your system settings. That's what it look like on my phone:
![изображение](https://user-images.githubusercontent.com/63293432/204542903-4bace240-7846-49de-ab48-76c00232088c.png)

**Comment by Dwynr** [comment]
Should be fixed in the next update.
