### ISSUE TITLE
Public link issue

### ISSUE THREAD

**Issue by eloffmarijan** [FilenCloudDienste/filen-mobile#134]
Problem while enabling public link.
When enabling public link, I get a invalid link.
I have to reopen the public link menu to get the valid link.
![Screenshot_20221204-203753_Filen](https://user-images.githubusercontent.com/101601874/205498683-a0ff3b6b-b2e6-4dc7-aa9f-ca6a5254d545.png)
Link i get when enabling: https://filen.io/d/[object Object]#!2kyHC31msLRMnnIwK1Cek0GfIKX4HtG3

**Comment by DanielProg39** [comment]
Checked it on my side, same issue

**Comment by Dwynr** [comment]
Will be fixed in the next update.
