### ISSUE TITLE
Date-sorted files are in scrambled order

### ISSUE THREAD

**Issue by privacytime101** [FilenCloudDienste/filen-mobile#140]
When I set the sort as "descending" under Date in a folder with a lot of files, it doesn't actually sort it correctly. Files with random dates are scattered throughout the list and it's very unorganized.

iOS 16.2, Filen 2.0.31

**Comment by jnolan7599** [comment]
Related: #101

**Comment by Dwynr** [comment]
Should be fixed in the next update.
