### ISSUE TITLE
DNS calls to api.filen.io even when app isn't being used. What's the rational?

### ISSUE THREAD

**Issue by jnolan7599** [FilenCloudDienste/filen-mobile#141]
Hello,

Per above, I'm seeing numerous calls/requests to api.filen.io, about two or three per hour, even when the app isn't loaded up/running. I'm not fond of my device being 'chatty' when its unused. May I ask why these DNS lookups are occurring?

v2.0.31

TIA.

**Comment by Dwynr** [comment]
Camera upload/isOnline checks, simple GET/HEAD calls, nothing special.
