### ISSUE TITLE
Android SAF/iOS Files Provider

### ISSUE THREAD

**Issue by Dwynr** [FilenCloudDienste/filen-mobile#150]
Implement SAF & iOS Files Provider.

Opens up a lot of opportunities, like syncing on Android, direct file access for iOS etc.

**Comment by nikolayhg** [comment]
are there plans to start working on this issue in 2023?

**Comment by mufeedali** [comment]
This is really the only truly "missing" feature in Filen for me right now. Would love to see this happen

**Comment by Dwynr** [comment]
iOS FileProvider implemented as of https://github.com/FilenCloudDienste/filen-mobile/commit/e642fc8324d7ba74ade8408ee377896b6319ead5

Internal QA stage started.
