### ISSUE TITLE
Pausing one upload pauses all uploads

### ISSUE THREAD

**Issue by Rainingmon** [FilenCloudDienste/filen-mobile#155]
When uploading multiple files through the app pausing one via the transfers page will stop all transfers being uploaded and not just the one selected to pause.
This issue does not affect auto camera uploads and only seems to be a bug when I manually upload files. I have only tested by trying to mp3, m4a and flac files.

Steps to reproduce:
1. Open android app and click the plus on the bottom of the screen and select "Upload Files"
2. Select multiple files (.mp3, .m4a, .flac) and upload
3. Head over to the transfer screen by clicking the loading circle bottom right
4. Pause an upload and watch as all other uploads also stop.  (Percentage never changes)
5. Unpause the paused upload and they will continue as normal

Also stopping one upload will also stop all uploads

App version 2.0.31 (Downloaded APK from github)
OS Version: Android 12
Phone: Samsung Galaxy A21s

Another minor bug I don't feel like making another issue for unless requested
When an upload is paused if you leave the transfers screen and then open it again the resume button changes back to saying pause instead of resume

**Comment by Dwynr** [comment]
Fixed in the next update.
