### ISSUE TITLE
Renaming a file leaves a leading period (.)

### ISSUE THREAD

**Issue by thetrotfreak** [FilenCloudDienste/filen-mobile#158]
**Steps to reproduce:**

1. Create a new file (on desktop), give it a name but no extension.
2. Wait for it to be synced to the cloud.
3. Add an extension by renaming it on your phone.
4. This will leave a **leading period** `(.)` in the file name.

> Tested on Windows 11 (OS build `22621.1105`) and phone (android 12).

> **Two-way** `sync mode` was used while testing, but I assume it is independent of the `sync mode`.

**Comment by Dwynr** [comment]
Thanks for the bug report! Could reproduce the issue and fixed it. Will be available in the next update.

Rel: https://github.com/FilenCloudDienste/filen-mobile/commit/4affff608e5ce14307d3b31a9bf3b91a4c90e8c4
