### ISSUE TITLE
Option to disable Cached Thumbnails iOS

### ISSUE THREAD

**Issue by Aystro** [FilenCloudDienste/filen-mobile#159]
It would be great if there was an option to disable Cached Thumbnails, as these are easily viewable in the iOS Files app.

**Comment by Dwynr** [comment]
Disabling thumbnail caching would mean that the app would have to re-download and re-convert all thumbnails in view everytime it is re-opened. Huge waste of bandwidth and compute for both parties. Not planned for now.
