### ISSUE TITLE
Preserve original timestamp in image metadata

### ISSUE THREAD

**Issue by skauertz** [FilenCloudDienste/filen-mobile#160]
iOS 16.2, Filen 2.0.31.

Right now, when uploading photos automatically on iOS, the original timestamp of when the photo was taken is lost. All that is available is the Modification Date, which seems to be updated by iOS every time the photo is opened in the Photos app. This makes it impossible to find out when an image was taken once it has been uploaded to the cloud.

Interestingly, when sharing an image with Filen via the built-in iOS share mechanism, the original timestamp is preserved along with the modification date, so it is possible.

The mobile app should preserve original timestamps for images when automatic upload is enabled. Even better would be naming the image files according to original timestamp date and time, like the "Documents" app does it, i.e.:

`2022-12-39 09.33.jpg`

or similar, which would allow sorting them in any file manager without having to inspect metadata.

**Comment by Dwynr** [comment]
Fixed in the next upcoming update.
