### ISSUE TITLE
[app issue] offline available and offline mode

### ISSUE THREAD

**Issue by Moon-Mind** [FilenCloudDienste/filen-mobile#166]
When i make a File offline available 
![image](https://user-images.githubusercontent.com/52799853/217496212-36367838-f578-4eca-a2cf-a93b15e9bf76.png)
then i remove all internet connections than and also kill the app as Prozess and Start in "offline mode"
![image](https://user-images.githubusercontent.com/52799853/217496449-910c882f-f489-4c0c-844a-f63775ba3475.png)
but i can not access the files that are offline available when i try to open them

also when i enabled the wifi in the "offline mode" i need to kill the app again to connect it to the internet

**Comment by Dwynr** [comment]
Will be fixed in the next update, thanks for reporting.
