### ISSUE TITLE
Choose a Folder Dialog Obscures A Folder

### ISSUE THREAD

**Issue by RDMillen** [FilenCloudDienste/filen-mobile#171]
![6000C584-CD34-42CF-8B49-140C23B014DC](https://user-images.githubusercontent.com/60128472/218199762-cc204962-aba5-4144-9e56-80da8a6254d7.jpeg)

The choose a folder upload dialog makes it difficult to select the folder at the bottom of a list. 

Potential to add a margin to push folders above the upload message or to relocate the upload button?

**Comment by Dwynr** [comment]
Will be fixed in the next update coming soon. Upload toast will be pushed above the last item in the list so it remains clickable. Thanks for reporting anyways.
