### ISSUE TITLE
[Feature Request] Notification

### ISSUE THREAD

**Issue by BabyOilJohnson** [FilenCloudDienste/filen-mobile#174]
Providing a notification feature will be nice, to know how much percentage downloaded/uploaded when we are outside of the app.

**Comment by neonota** [comment]
+1

**Comment by telrod11** [comment]
Yes , please!

**Comment by Dwynr** [comment]
Is already implemented in the next update, thanks for your suggestion!

**Comment by telrod11** [comment]
Any idea when the next release may drop?   

(Perhaps a status update for all of us here or on Reddit?)
