### ISSUE TITLE
[Bug] iOS zooming doesn't update the zooming coordinates

### ISSUE THREAD

**Issue by der-pixel** [FilenCloudDienste/filen-mobile#182]
When you open an image and you zoom-in, the next time you zoom, it still uses the original coordinates, which means that when (after zooming-in) you zoom-in again, or zoom-out, it will move to a different place. because it's like you are clicking on the original image, not in the new "cropped" image.

Example:

Let's say that you have a frontal picture of a face, and you zoom-in the nose. Then afterwards, while being zoomed-in the nose, you decide to zoom to the top of the nose. The expected behavior would be that you end-up being zoomed-in on the top of the nose, but instead, what happens is that it moves the zoom to the forehead, because where you touched in the screen to zoom-in to the top of the nose, is where the forehead was in the original image.

iOS 16.3.1

**Comment by Dwynr** [comment]
We will implement a complete new and better image viewer in the near future. Thanks for reporting anyways! Will keep the issue open until it's implemented.
