### ISSUE TITLE
MobileMedia does not sync automatically

### ISSUE THREAD

**Issue by joaobarcia** [FilenCloudDienste/filen-mobile#185]
Hi, the camera upload function does not upload my photos automatically. To upload photos I have to open the menu Settings > Camera upload > Albums. 

Opening this menu seems to trigger some forced sync. The photos taken since the last upload are then added to the upload queue.

I'm using v. 2.0.31 on Android. Happy to send any relevant logs on further information.

**Comment by Dwynr** [comment]
Use the latest version (2.0.46 at least), syncing has been fixed.
