### ISSUE TITLE
Unlock with Touch ID does not work on iPad

### ISSUE THREAD

**Issue by dragani** [FilenCloudDienste/filen-mobile#189]
Unlock with Touch ID doesn't work on iPad in the latest app version 2.0.44. I have enabled 'Biotmetric/PIN code authentication' option in the settings but when I exit the app and open it again I'm greeted the plain PIN code unlock pad:

![image](https://user-images.githubusercontent.com/93045850/224470717-2556ec7b-7b1a-4f3b-ac3a-59bc082b8ba2.png)

Tapping the fingerprint button doesn't do anything. I have tried disabling and enabling the option and reinstalling the app.

Unlock with Face ID works fine with my iPhone.

**Comment by Dwynr** [comment]
Fixed in the next update.
