### ISSUE TITLE
Can't share link

### ISSUE THREAD

**Issue by BabyOilJohnson** [FilenCloudDienste/filen-mobile#190]
I can't share public link using the share button in the filen to other apps, getting these toast messages.
![Screenshot_20230314-003304_Filen](https://user-images.githubusercontent.com/101601874/224804257-c5da1ee0-7bbd-4b98-b182-6f535b2a1efe.png)
![Screenshot_20230314-003132](https://user-images.githubusercontent.com/101601874/224804277-c45e9c2d-0edf-4cf8-b545-407d3d7d0e01.png)
![Screenshot_20230314-003125_Filen](https://user-images.githubusercontent.com/101601874/224804282-e954f6da-2ec7-4915-9426-15f018e4ecec.png)
![Screenshot_20230314-003109_Filen](https://user-images.githubusercontent.com/101601874/224804287-02d6fbf2-411c-4d6f-b181-deb4e074ef1a.png)

**Comment by Dwynr** [comment]
Without a proper bug report (OS version, Phone info, other relevant info) we can't really do anything. Not reproducible on our end.

**Comment by BabyOilJohnson** [comment]
Device Model:  Samsung A30
Android Version:  11
Version: 2.0.46

Got this error

>
