### ISSUE TITLE
[enhancement] fix sorting problem

### ISSUE THREAD

**Issue by maikella** [FilenCloudDienste/filen-mobile#193]
![image](https://user-images.githubusercontent.com/97262283/225340851-699f4119-af6c-4f46-b43e-ab8f67fca966.png)

**Comment by DanielProg39** [comment]
It seems that you use sorting by the file type, just change it in appropriate settings: Button on upper right corner -> Sort by -> select what you need.

**Comment by DanielProg39** [comment]
I see, it seems that sorting is implemented incorrectly for numbers, in the same way as for letters: it sorts them figure by figure
