### ISSUE TITLE
[Security] Disable iPhone passcode unlock with FaceID.

### ISSUE THREAD

**Issue by Barraguesh** [FilenCloudDienste/filen-mobile#198]
This issue comes from this Reddit post: https://www.reddit.com/r/filen_io/comments/11i87sn/filen_access_vulnerability_when_using_iphone_face/

Basically, Face ID unlock on Filen can be unlocked by the iPhone passcode if Face ID fails. Other apps, like banking apps, don't enable this. After the latest attacks on social gatherings where people snoop the passcode before stealing the device and accessing all the apps inside (more details inside the Reddit post), I also believe Filen should change the behavior and only support Face ID without phone passcode or app PIN.

**Comment by Dwynr** [comment]
Added in the next release.
