### ISSUE TITLE
Automatic camera upload does not work when app in in background 

### ISSUE THREAD

**Issue by cschle** [FilenCloudDienste/filen-mobile#199]
When shooting images with the filen app in background pictures are not uploaded.
bringing the filen app to foreground triggers the upload.
the usual 'do not optmize' settings are in place.
Pixel 6a, Android 13, Feb patch level

**Comment by skauertz** [comment]
I am noticing the same on iOS, Filen v2.0.46.

**Comment by Yrlish** [comment]
Experiencing the same problems on Android, app version 2.0.58 on my nothing phone 1.

**Comment by CostcoFanboy** [comment]
Shame there's dead silence on such an important feature.

**Comment by Dwynr** [comment]
We are working on bringing this feature to both Android and iOS using silent push notifications in the near future. It's sadly not as easy as some portray it to be. Working on it though.

**Comment by Yrlish** [comment]
@Dwynr how is it going?

**Comment by m1chj** [comment]
You could maybe try to implement manual check feature in case the background upload is unreliable and killed by different battery saving mechanisms? It's gonna be a lot of pain providing a feature that works for everyone with different devices. pCloud has something like that ("Scan Now") and once tapped, it creates notification for each file so the upload is somewhat safe in the background

![Screenshot_20230620_185904](https://github.com/FilenCloudDienste/filen-mobile/assets/45080190/84f82f37-2c1d-46aa-98e9-cc47aeef945c)

![Screenshot_20230620_185932](https://github.com/FilenCloudDienste/filen-mobile/assets/45080190/b5642666-2eb6-4184-ab08-9cfc8e744318)

**Comment by Dwynr** [comment]
Implemented in the next update.

**Comment by CostcoFanboy** [comment]
> Implemented in the next update.

Absolutely fantastic work. Sorry I know it's closed but I don't want to just whine about this then not thank you for implementing it when it's actually fixed.

Thank you!

**Comment by kyuuaria** [comment]
> Implemented in the next update.

@Dwynr Nice work, imo this is a much needed feature. When can we roughly expect the next update?
