### ISSUE TITLE
Increase HASH iteration to meet OWASP recommendation.

### ISSUE THREAD

**Issue by BirdInFire** [FilenCloudDienste/filen-mobile#200]
Hello since Security is in the core of your app i must clear some point : 

The hashing password as stated in your witepaper is 200.000 but the minimum recommended (2023) value by [OWASP](https://en.wikipedia.org/wiki/OWASP) is now 210,000 for PBKDF2-HMAC-SHA512.

In your Whitepaper page 5 you state : 

```
The password hash is computed as follows:
Salt= cryptographically secure generated random 256 character value
Hash= SHA-512
Iterations= 200.000
Bit Length= 512
Derived Key = PBKDF2(password, salt, iterations, hash, bitLength)
```

on page 8 you also state : 

```
Public links can be configured to expire or be password protected. The password
hash for the public link will be derived from the original password using
PBKDF2(password, salt, iterations, hash, bitLength), where salt is a random 256
bit string, iterations set to 200.000, hash set to SHA-512 and bitLength set to
512.
```

Witch mean that by current standard you are 10.000 not enough to follow security recommendation.

I do recommend you to push it to 250.000 like that you are a little higher than the recommendation.

I also do recommend to move the Argon2 hashing client side too since hash server side is useless in case where the server is taken over, when the client will send a file they just have tho save the unhashed version before it's hashed on the server.

The whitepaper also do not specify if your using argon2d, argon2i or argon2id.

I know nothing beat a good old long complicated password, but not meeting actual recommendation can be bad for your security images (why i ask to increase it and add a way for old user to have the update too (in the client)).

**Comment by skauertz** [comment]
Really? Are 5% more hashing iterations going to make any significant difference?

**Comment by BirdInFire** [comment]
> > It's the official recommandation for all cryptography based services the "increase percentage" is irrelevant.
> 
> On the contrary, it is very relevant. What you are saying is basically, if a user's password can be hacked in 100 ms, increasing that time to 105 ms will save them.

it seem you don't actually know how security is done, and how bad it is to not follow the recommendation when it come to this kind of thing.

Some already say that Filen aren't secure due to some mistake (now fixed) of them in the past.

What do you think will happen if they start to not follow security recommendation that every (even password manager) do follow ?

Finally increase of 5% do not increase only of 5 ms the cracking time, check how do work hashing, and how do work brute-force attack on it work before saying false statement like that.

**Comment by skauertz** [comment]
> it seem you don't actually know how security is done, and how bad it is to not follow the recommendation when it come to this kind of thing.

Oh, I don't pretend to be a security expert, but I do believe I have a pretty good grasp on how hashing works. 

Anyway, you're clearly not open to constructive discussion, so this ends here for me.

**Comment by Dwynr** [comment]
> What do you think will happen if they start to not follow security recommendation that every (even password manager) do follow ?

If you would have actually skimmed through whitepapers of the most popular password managers you would've seen that most of them don't follow the 2023 OWASP recommendation. Bitwarden for example uses SHA256 PBKDF2 with 100.000 iterations. Comparing to others is not the point though.

We've carefully chosen the hash method and iteration count when we designed the system. You have to keep in mind that not everyone who uses the platform runs on good hardware. Increasing the iterations count always comes with the downside of operations taking longer.

Also what @skauertz said is correct and simple math.

**Comment by BirdInFire** [comment]
> > What do you think will happen if they start to not follow security recommendation that every (even password manager) do follow ?
> 
> If you would have actually skimmed through whitepapers of the most popular password managers you would've seen that most of them don't follow the 2023 OWASP recommendation. Bitwarden for example uses SHA256 PBKDF2 with 100.000 iterations. Comparing to others is not the point though.
> 
> We've carefully chosen the hash method and iteration count when we designed the system. You have to keep in mind that not everyone who uses the platform runs on good hardware. Increasing the iterations count always comes with the downside of operations taking longer.
> 
> Also what @skauertz said is correct and simple math.

First it's the time used on Client side who do know the password, but it increase the time to crack the hash (real time based on the complexity of the password hashed), so no increase 5% do not only increase 5ms TO CRACK it since this time is based on the password complexity.

it seem your data is outdated : 

And the owasp recommandation are 210.000 with sha512 .. and 600.000 on 256: 

if you continue to claim that these size are other please provide source because i do it when you do not.

source : https://www.ghacks.net/2023/02/02/bitwarden-to-increase-its-server-side-iterations-to-600000-heres-how-to-set-it-manually/
source : https://www.twit.community/t/bitwarden-to-increase-its-server-side-iterations-to-600-000/13981
source : https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2
source : https://palant.info/2023/01/23/bitwarden-design-flaw-server-side-iterations/

**Comment by Dwynr** [comment]
Sorry if you are misunderstanding it, maybe it's the language barrier.

https://bitwarden.com/help/bitwarden-security-white-paper/

https://bitwarden.com/_gatsby/image/ec348d76bb61b958452ffa351bf687a7/bf84771ac99fbcd0cc041ee9927e1c0c/overview-of-keys-generated.avif?eu=8c8904e1e19bfbd45969a9873c70323fe03e02f9a85137d96962b7fb4aaf9e8f2da11a5474932ce7246c5ddb81e841b864ce7b3048eed58995b81ca2e833a209008b52eb6fb42451502e92f9b0f154476ecf195ea8d59e5aa56c788ca1f7f733134f0372f52befd4afb76620e6d26c71bff2e5303b97ef67e75000078d4270aa6ce6d7d92c1b8f95cb43a5b1b7ed5cb1fee56f4e1788b57c5b3513000aef2de9f0b15278687d475a66c8f90dc16997e2391b342b0c5a0bf53469815de4337796a6bdf8089e6724b7b5926439c5def9d5b34fee7b32b29b39e9dc6c&a=w%3D850%26h%3D478%26fm%3Davif%26q%3D75&cd=2022-01-19T18%3A14%3A55.076Z

They just recently increased it in Feb. 2023. Accounts created prior still use the old iteration count (if not _manually_ increased). Increasing the iteration count in the code does not automatically apply to all accounts. Authentication would have to be versioned, and the new iteration count would only apply to newely created accounts. We also hash again server side using argon2id by the way.

A 10.000 iteration count increase would result in hashing operations taking 5% longer on average. The 100ms to 105ms mentioned by @skauertz is just for demonstration simplicity. Depending on the hardware the user runs on this _can_ be a slowdown across the application. We need to balance performance and security.

**Comment by BirdInFire** [comment]
> Sorry if you are misunderstanding it, maybe it's the language barrier.
> 
> https://bitwarden.com/help/bitwarden-security-white-paper/
> 
> https://bitwarden.com/_gatsby/image/ec348d76bb61b958452ffa351bf687a7/bf84771ac99fbcd0cc041ee9927e1c0c/overview-of-keys-generated.avif?eu=8c8904e1e19bfbd45969a9873c70323fe03e02f9a85137d96962b7fb4aaf9e8f2da11a5474932ce7246c5ddb81e841b864ce7b3048eed58995b81ca2e833a209008b52eb6fb42451502e92f9b0f154476ecf195ea8d59e5aa56c788ca1f7f733134f0372f52befd4afb76620e6d26c71bff2e5303b97ef67e75000078d4270aa6ce6d7d92c1b8f95cb43a5b1b7ed5cb1fee56f4e1788b57c5b3513000aef2de9f0b15278687d475a66c8f90dc16997e2391b342b0c5a0bf53469815de4337796a6bdf8089e6724b7b5926439c5def9d5b34fee7b32b29b39e9dc6c&a=w%3D850%26h%3D478%26fm%3Davif%26q%3D75&cd=2022-01-19T18%3A14%3A55.076Z
> 
> They just recently increased it in Feb. 2023. Accounts created prior still use the old iteration count (if not _manually_ increased). Increasing the iteration count in the code does not automatically apply to all accounts. Authentication would have to be versioned, and the new iteration count would only apply to newely created accounts. We also hash again server side using argon2id by the way.
> 
> A 10.000 iteration count increase would result in hashing operations taking 5% longer on average. The 100ms to 105ms mentioned by @skauertz is just for demonstration simplicity. Depending on the hardware the user runs on this _can_ be a slowdown across the application. We need to balance performance and security.

it don't actually change the fact you do not follow the actual security "recommandation" of 210.000 (since you use 200.000 and it's again a bad ads on your security practice) and sadly i think i will start to find another company if you do not do it since i won't trust my safety on company that do not follow ACUTAL security change (lastpass was hacked due to that since they never have changed their iteration of the hash).

I think increasing from 200.000 to 210.000 (like the recommendation) will have like a millisecond more to follow recommendation but if you want to be labelled as bad at security ok for you but don't cry when customer will avoid you for that.

Customer that search E2EE have many time high expectation of the encryption and it's time you understand that.
