### ISSUE TITLE
[Feature Request] Sync options the same as in the desktop application.

### ISSUE THREAD

**Issue by JumpProg** [FilenCloudDienste/filen-mobile#202]
Implement the sync solution as in the desktop application (selection of different folders etc.):

Sync options:
-     two way,
-     local to cloud,
-     cloud to local,
-     local backup,
-     cloud backup.

**Comment by Moon-Mind** [comment]
https://github.com/FilenCloudDienste/filen-mobile/issues/150 

Already asked

**Comment by Dwynr** [comment]
Duplicate.
