### ISSUE TITLE
[BUG] Last IOS update broke FACEID

### ISSUE THREAD

**Issue by BirdInFire** [FilenCloudDienste/filen-mobile#203]
Since last update FaceID unlocking is broken and always ask pin where it worked before the update.

2.0.51

**Comment by dragani** [comment]
I was just about to report the same issue.

**Comment by Dwynr** [comment]
Looks like a regression from updating all of our expo dependencies. Will take a look at submit a hotifx update.

**Comment by postprivee** [comment]
tried to install on a new device
steps: first launch + biometric/pin code authentication on
result: face id permission not asked/enabled

**Comment by dragani** [comment]
2.0.52 fixed Face ID but broke Touch ID again...

**Comment by Dwynr** [comment]
2.0.53 fixed the issue for faceID aswell.
