### ISSUE TITLE
[Feature Suggestion] Option to compress or lower the resolution of the photos before uploading

### ISSUE THREAD

**Issue by AsuxAX** [FilenCloudDienste/filen-mobile#206]
I think it would help with preserving space.

**Comment by DanielProg39** [comment]
Although it should be turned off completely by default. Also, an option to delete metadata (or specific metadata) would be great, I suppose

**Comment by BirdInFire** [comment]
i'm for it but only if disabled by default, having my HQ pictures destroyed (in quality) by missing a feature would upset many gal or guy.
the metadata option must also be off by default, since some people who do picture themselves actually add these metadata themselves and also would be very upset to see them gone.

**Comment by AsuxAX** [comment]
> i'm for it but only if disabled by default, having my HQ pictures destroyed (in quality) by missing a feature would upset many gal or guy.
> the metadata option must also be off by default, since some people who do picture themselves actually add these metadata themselves and also would be very upset to see them gone.

Same.
It of course should be disabled by default.

**Comment by BirdInFire** [comment]
> > i'm for it but only if disabled by default, having my HQ pictures destroyed (in quality) by missing a feature would upset many gal or guy.
> > the metadata option must also be off by default, since some people who do picture themselves actually add these metadata themselves and also would be very upset to see them gone.
> 
> Same. It of course should be disabled by default.

Why not (like Icloud do) in the settings having a line who appear until you close it with ("You can reduce the size of your picture and/or remove metadata" and we have choice a X to close this line or clic on the link and the app show us these two settings with a switch to enable them or not)

**Comment by Dwynr** [comment]
Added in the next release (optional of course).
