### ISSUE TITLE
Unable to upload files or start camera backup

### ISSUE THREAD

**Issue by ruben-tura** [FilenCloudDienste/filen-mobile#207]
Android 13, MIUI 14, Xiaomi MI 11 Lite 5G

App version 2.0.54, downloaded from github releases.

When I touch "upload a file", nothing happens.
Also, when I go into "Albums", to select which ones to upload with the automatic upload, it just infinitely loads.

It looks like it's maybe missing some permissions to see the storage? 

The app also crashes when, initially, it asks for video / photo permissions, which may be a symptom of something.

**Comment by Dwynr** [comment]
Thanks for reporting, looks like an Android 13 only issue, thats why we did not catch it earlier. Will look for a fix.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-mobile/commit/e7044c46d35fd45237f9097c4370901a0fef3c3a
