### ISSUE TITLE
Extra space

### ISSUE THREAD

**Issue by BabyOilJohnson** [FilenCloudDienste/filen-mobile#208]
The options menu having more space freely, its wasting the area.
![Screenshot_20230412-133454_Filen](https://user-images.githubusercontent.com/101601874/231400983-2e98f8a6-b2f2-4487-b837-3dd09beaafae.png)
![Screenshot_20230412-133645_Filen](https://user-images.githubusercontent.com/101601874/231400999-d82eb860-7b19-4dde-9661-eb3e149613f5.png)
![Screenshot_20230412-134652_Filen](https://user-images.githubusercontent.com/101601874/231401008-4e125ed3-82bc-41c3-af5e-e72822dd2e72.png)

**Comment by DanielProg39** [comment]
I have the same issue
