### ISSUE TITLE
[Bug] Glitching options menu

### ISSUE THREAD

**Issue by BabyOilJohnson** [FilenCloudDienste/filen-mobile#209]
Weird bug in the options menu.
https://user-images.githubusercontent.com/101601874/231405152-596a779c-ec46-4b57-ba85-77951d743329.mp4

**Comment by Dwynr** [comment]
Fixed: https://github.com/FilenCloudDienste/filen-mobile/commit/4477a797917a99222b741d5642cdeb396846b7d5
