### ISSUE TITLE
[feature request] Material You

### ISSUE THREAD

**Issue by muznyo** [FilenCloudDienste/filen-mobile#211]
Latest versions look very iOS-y on Android, especially settings.

In my opinion, the design looks off.

Android app could use [Material You](https://m3.material.io/) Design Language, which fits Android ecosystem more.

**Comment by DanielProg39** [comment]
I totally agree, M3 definitely looks better than the stale and dry iOS UI, especially on Android, as it allows flexible theming and is more authentic with the whole system. Google Drive is the best example, even though it is not perfect in terms of UX and the Material You features implemented there.

**Comment by BabyOilJohnson** [comment]
Yeah, it's like using iOS app on Android. So please give Android ish UI other than copying down iOS UI.
