### ISSUE TITLE
Edit 2.0.57 FIXED - Android build 2.0.56 - stuck on uploading (Camera Upload)

### ISSUE THREAD

**Issue by telrod11** [FilenCloudDienste/filen-mobile#215]
Camera Upload (Filen 2.0.56)
Samsung S20 FE 5g 
Android 12

App was stuck uploading, (perhaps one file?), took more photos / videos and the numbers changed, but with teh same issue, approximately 20 photos left to upload.

![Screenshot_20230417_081129_Filen](https://user-images.githubusercontent.com/105058921/232482556-f1bd0e64-0fd3-42be-b69c-24f35e79627b.jpg)

**Comment by Dwynr** [comment]
Looking into it.

**Comment by telrod11** [comment]
> Looking into it.

Thank you!

**Comment by telrod11** [comment]
Downloaded 2.0.57, installed clean, all my photos / videos uploaded as they should.

Took 5 more pics, and they also completed successfully!

Thanks @Dwynr !!

(attachments)
![Screenshot_20230418_081240_Filen](https://user-images.githubusercontent.com/105058921/232776471-3f59f882-fe26-415f-aa1b-2b230cd45c45.jpg)
![Screenshot_20230418_081336_Filen](https://user-images.githubusercontent.com/105058921/232776474-8bbe85a9-0151-4d9e-8363-897b96879a02.jpg)
![Screenshot_20230418_081035_Filen](https://user-images.githubusercontent.com/105058921/232776476-6fad2692-dd96-4e02-ba57-4e881d98e80b.jpg)

**Comment by Dwynr** [comment]
Finally. All it took was proper path encoding and decoding where needed.

**Comment by telrod11** [comment]
> Finally. All it took was proper path encoding and decoding where needed.

Well, I'm a happy camper!    Glad you guys were able to get it sorted!!
