### ISSUE TITLE
[Bug] Some settings don't work

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#216]
In the v2.0.56 (Android), pressing "Change email or password" and "Enable Two Factor Authentication" does nothing.

**Comment by Dwynr** [comment]
They are supposed to open your default browser since those settings are only meant to be modified on our website. Can't reproduce though. Did you not setup a default browser on your device?

**Comment by DanielProg39** [comment]
I did. But after some experiments it seems that it works only if your default browser is Chrome. Try with something else, e.g. Firefox

**Comment by DanielProg39** [comment]
Problem still exists in 2.0.57
