### ISSUE TITLE
[Android] Crash when clicking on Albums (Camera Upload)

### ISSUE THREAD

**Issue by Mangoes** [FilenCloudDienste/filen-mobile#217]
After clicking on Albums in Camera Upload, it displays the list of folders for 1 second and the app crashes.

Also, after updating the app, it started uploading videos from the phone. While doing this, clicking on all the menus in the settings does nothing (it isn't possible to enter the sections). When it is done uploading, it works again.

I have tried deleting all the app settings and data (= uninstall  - reinstall). No change. 

Version: 2.0.57 (2.0.46 doesn't have this problem).
Device : Samsung S20

Thanks.

**Comment by Dwynr** [comment]
Fixed it with a patch for expo. Should be working now in the latest release version.
