### ISSUE TITLE
[Bug] Raw Photo taken with iPhone 14 pro are not synced and does not show up in the photo picker.

### ISSUE THREAD

**Issue by samy570** [FilenCloudDienste/filen-mobile#221]

**Comment by Dwynr** [comment]
Thanks for reporting. Are you talking about Apple Pro RAW files with the .dng file extension?

**Comment by samy570** [comment]
Yes Apple Pro RAW file with .dng format.

**Comment by Dwynr** [comment]
Should be fixed in the next update.
