### ISSUE TITLE
[Feature request] - on Android app user should can choose download directory and show a confirm dialog when delete a file/directory and when upload a file with same name to replace another

### ISSUE THREAD

**Issue by gpdevsoft** [FilenCloudDienste/filen-mobile#223]
when we download a file on Android device we can't choose the folder where download becauese the app using always the default Download directory  

when user delete some file or directory no confirmation dialog is show

when user upload a file with same name of antother already in cloud storage it would be usefuel show a dialog to ask if you want replace or upload changing file name

**Comment by Dwynr** [comment]
Duplicate, closing.
