### ISSUE TITLE
Bugs when downloading files

### ISSUE THREAD

**Issue by entropy1453** [FilenCloudDienste/filen-mobile#226]
- if there is a space in the file name, it creates an empty file beside the main one
- if the file name is in Cyrillic, then the downloaded file does not display it correctly
Android 8.1
![IMG_20230428_182355](https://user-images.githubusercontent.com/132078608/235189588-9767c5d6-0cbd-4747-93b4-10ee7bf61876.jpg)

**Comment by Dwynr** [comment]
This only happens on old Android versions and is a bug in the underlying filesystem lib we use. Need to wait until peer dependency is fixed.
