### ISSUE TITLE
Can't upload

### ISSUE THREAD

**Issue by BabyOilJohnson** [FilenCloudDienste/filen-mobile#227]
I can't upload files especially like apks, pdf, documents etc from the file manager to filen. But i can upload pictures, audio and videos without problem.
![Screenshot_20230501-134312_Filen](https://user-images.githubusercontent.com/101601874/235428336-5f2ad576-692a-4643-ba63-e66c91fdcac4.png)

**Comment by joewood9364** [comment]
I'm having the same issue. I think it may be due to the app only requesting media file access when it really needs management of all files permission?

**Comment by DanielProg39** [comment]
This is a very old issue, it occurs only if you upload files using share function from file explorer, gallery or other app. If you upload files through "Upload files" or "Upload from gallery" options in the Filen app, everything works properly.

**Comment by joewood9364** [comment]
> This is a very old issue, it occurs only if you upload files using share function from file explorer, gallery or other app. If you upload files through "Upload files" or "Upload from gallery" options in the Filen app, everything works properly.

Would still appreciate a fix for this issue.
