### ISSUE TITLE
2.0.58 Camera Upload Stall

### ISSUE THREAD

**Issue by telrod11** [FilenCloudDienste/filen-mobile#229]
Camera Upload appears to be working as it should, but each time I refresh, I'm getting *five* photos / videos, that it appears filen is missing.

It will try and upload for five minutes or so, then say "everything uploaded".

I'll see this with each refreshed start of the app.

![Screenshot_20230503_054038_Filen](https://user-images.githubusercontent.com/105058921/235895222-8a5022a1-8cef-47d3-b698-905df80ebfdd.jpg)

**Comment by Dwynr** [comment]
Should be fixed in the next release.
