### ISSUE TITLE
[Feature-request] - Enable preview of MOV and HEIC format in Android

### ISSUE THREAD

**Issue by vishnucoder1** [FilenCloudDienste/filen-mobile#230]
Please add more file formats to preview from Android like HEIC, MOV etc

**Comment by Mangoes** [comment]
Still also missing thumnails for HEIC on Android.

Filen is currently unusable to store photos on Android, as the camera uploaded file names are just numbers, so we can't see what is what.

Been asking for this for 1.5 years already.

Hope it wasn't forgotten. Thanks.

**Comment by Dwynr** [comment]
Experimental support for HEIC on android will be added in the next update. Should work for Android 10+ with HEIC format support.
