### ISSUE TITLE
[Feature-Request] - Add download option by selecting a folder

### ISSUE THREAD

**Issue by vishnucoder1** [FilenCloudDienste/filen-mobile#231]
Currently download option is only available for folder. It will be convenient to select and download individual folder.

**Comment by skauertz** [comment]
I don't know, I can download single files to local storage just fine.

**Comment by skauertz** [comment]
Single folders can't be downloaded indeed.

**Comment by jont4** [comment]
I think this request is related to #150

**Comment by Dwynr** [comment]
We will add folder downloads to the app in an upcoming update.

**Comment by Dwynr** [comment]
Added.

https://github.com/FilenCloudDienste/filen-mobile/pull/288/commits/01b95cec763f911c7226247495f43e1d61a9e053
