### ISSUE TITLE
[Bug] - Thumbnail missing for video files

### ISSUE THREAD

**Issue by vishnucoder1** [FilenCloudDienste/filen-mobile#232]
Currently using version 2.0.58

Thumbnails are missing for some video files.

**Comment by Mangoes** [comment]
Missing for photos like HEIC on Android too.

Been asking for this for 1.5 years already.

Hope it wasn't forgotten. Thanks.

**Comment by Dwynr** [comment]
Not a bug. Since we create thumbnails client side, we only download the first 8-16 chunks of the video and try to create a thumbnail of those. Works for most videos, but not for all. We plan on implementing a better thumbnail generation function in the future.
