### ISSUE TITLE
Possibility to specify the backup destination folder + sync options the same as in the desktop application.

### ISSUE THREAD

**Issue by JumpProg** [FilenCloudDienste/filen-mobile#234]
Currently, the mobile application allows you to backup (photos, videos) from different folders into one specific folder - then it creates a mess, as everything is in one bag.
Is:

```
> /phone/camera to /cloud/photos
> /phone/whatsapp_image/ to /cloud/photos

```
It should be possible to specify the backup destination folder.
Example.
```
/phone/camera  to  /cloud/photos/camera
/phone/whatsapp_image/  to  /cloud/photos/whatsapp_image
```

In additional: Sync options the same as in the desktop application.
https://github.com/FilenCloudDienste/filen-mobile/issues/202

**Comment by Dwynr** [comment]
Duplicate.
