### ISSUE TITLE
Android: GUI freeze after deselect public link, App Version 2.0.58 (2058)

### ISSUE THREAD

**Issue by dhcgn** [FilenCloudDienste/filen-mobile#242]
This behavior is reproducible, App must be stopped and started again to regain responsibility. 

Version: 2.0.58 (2058)

https://github.com/FilenCloudDienste/filen-mobile/assets/6566207/5747e530-4543-48ce-92e7-985a57944777

**Comment by Dwynr** [comment]
Will take a look and include a fix in the next update! Thanks for reporting :)
