### ISSUE TITLE
Photos tab - no photos uploaded

### ISSUE THREAD

**Issue by telrod11** [FilenCloudDienste/filen-mobile#243]
2.0.60 RC 2

Photos page is empty.

Home shows all recent uploads, as does cloud .

Force app stop, clear cache, restart renders same results

**Comment by telrod11** [comment]
![Screenshot_20230616_071952_Filen](https://github.com/FilenCloudDienste/filen-mobile/assets/105058921/df21636f-4ace-4866-a7d1-66ff945ec8a9)

**Comment by Dwynr** [comment]
Did you maybe change your camera upload destination folder? That'd explain why it's showing nothing.

Cannot reproduce.

I would also ask to always report issues with a minimal reproducible example. Can't do much with a screenshot.

**Comment by telrod11** [comment]
No change.

All I did was update to latest RC, and the screen populates as I reported.   

Do you want me to drop back to the prev build, and report back?
