### ISSUE TITLE
FR: Use win32 sandboxing

### ISSUE THREAD

**Issue by hj-collab** [FilenCloudDienste/filen-mobile#252]
Hi,

Windows have introduced sandboxing for classic win32 applications. It will drastically improve the security of Windows users and prevent any vulnerability in Filen harming the system as the process will be isolated.

Build instructions given here. https://github.com/microsoft/win32-app-isolation

**Comment by IkelAtomig** [comment]
That's a good move from Microsoft to be honest. Kinda of making it like QubesOS.

This should be moved to [Filen Cloud Dienste/Filen-Desktop](https://github.com/FilenCloudDienste/filen-desktop) Repo.

---

P.S. Wait till it is moved and don't close this issue for being in the wrong repo.
