### ISSUE TITLE
[Android] Transfers stop when screen is off and also when app is in background

### ISSUE THREAD

**Issue by Mangoes** [FilenCloudDienste/filen-mobile#26]
Hi, 

This issue is using the latest Samsung Galaxy S phones (android 11).

I have tried:

1. disabled battery optimizations
2. lock the app in memory
3. leaving the phone on a full night, the next day when opening the screen the app was still running in the foreground, but nothing was transferred. (As soon as I powered on the screen the transfer continued again from where it had paused the day before).

The only way to keep the transfers running:

1. keep the screen on and the app must be active in the foreground
2. if I want to use another app,  the only way for the transfers not to stop is to run filen + the other app in split screen (so both apps are active in the foreground on the screen)

How it should work:

1. All the other apps (Mega, Onedrive, Gdrive, download managers, etc...) have a progress notification that keeps the transfers going  even if the app is in the background, or the screen is off.
2. Filen doesn't have this.

Please fix this.
Many thanks.

**Comment by DanielProg39** [comment]
I just wanted to report the same issue. It exists on the other phones too (e.g. Xiaomi). When uploading small files you simply don't pay attention to that but when yesterday I was uploading large ~2 Gb files I noticed that if I open other app keeping Filen in background, it will stop the upload pretending to continuing it, however will consumpt a huge amount of energy.
Suggestions given in a previous comment are great and I fully agree with its author.

**Comment by AndrewNoonan2004** [comment]
This issue appears fixed for me
