### ISSUE TITLE
Many menus are truncated

### ISSUE THREAD

**Issue by lyonelf** [FilenCloudDienste/filen-mobile#265]
Hi,

On a P20 Lite 5"84 inches, so many menus are not fully visible.

I try to transate shorter but for some, it' snot possible.

Who can you do for fix that?

Menus on double lines is possible?

**Comment by Dwynr** [comment]
Unfortunately the only fix for that would be shorter translations. Our community helps us with translations. If you have suggestions or a better version just create a pull request.
