### ISSUE TITLE
Feature - Filename on thumbnail

### ISSUE THREAD

**Issue by telrod11** [FilenCloudDienste/filen-mobile#266]
How about having the filename on the thumbnail?

Would make it a lot easier to manage the duplicates

**Comment by Dwynr** [comment]
Not exactly sure what you mean, can you elaborate?

**Comment by telrod11** [comment]
Like this....

Now the way FIlen works, if you rename files (photos), it will backup (probably) both.

Would be nice to see the files in thumbnails with the original name IMG1236, and then the one you renamed, that you really want to keep.

This would make it easier to delete them without having to go full screen, where you do display the filename, and where also, we have no ability to delete from full screen.

![Thumbs](https://github.com/FilenCloudDienste/filen-mobile/assets/105058921/1055ec5b-0bdc-4f54-a8f3-1ed1009354d3)

**Comment by Dwynr** [comment]
Ah I get it, could be a toggle option. Will consider it for next update.
