### ISSUE TITLE
Uploading larger files -ereadtimout

### ISSUE THREAD

**Issue by telrod11** [FilenCloudDienste/filen-mobile#268]
Videos tested were around 200mb, and I can't finish an upload without:

Error : etimedout or ereadtimedout

Also, opened a ticket with support on this - android auto uploads are painfully slow.   I suppose these two issues are connected.

The process in the auto upload code to start 15 files , finish those and then wait two minutes to try and start a new batch makes this even more frustrating.

**Comment by Dwynr** [comment]
Not reproducible, not enough info.
