### ISSUE TITLE
[Feature Request] Auto-lock application and Unlock using Biometrics or PIN

### ISSUE THREAD

**Issue by nethzsumang** [FilenCloudDienste/filen-mobile#27]
It would be nice if there is a feature which the user can provide how many seconds the app stays unlocked.
After those number of seconds of inactivity has elapsed, the application will automatically lock itself.

Also, it must have an option to unlock the application using biometrics (face ID or fingerprint) or PIN.

**Comment by Dwynr** [comment]
This feature is already implemented in the upcoming release.
