### ISSUE TITLE
Picture download bug

### ISSUE THREAD

**Issue by hruzgar** [FilenCloudDienste/filen-mobile#270]
So I selected 300 pictures and clicked "download". The download began and there was a round indicator of the download. When I clicked on that indicator, the download page opened. But the problem is now the program is completely unresponsive. I can see the images downloading but I can't click. anywhere. It's like the app froze. This is also fully reproducable. It happens 100% of the time.
Device: Nokia G50, Android 13

**Comment by Dwynr** [comment]
Should be fixed in the next update. We've completely overhauled the transfers screen/indicator.
