### ISSUE TITLE
Filen iPad app cuts off top and bottom of photo

### ISSUE THREAD

**Issue by apharp** [FilenCloudDienste/filen-mobile#278]
To clairfy, the actual image is NOT being altered. It seems to just be an issue with the image viewer used by the Filen app in landscape.

To reproduce:
1) Download the original photo below and upload to it Filen using any supported method.
2) Open the Filen app on iPad and rotate to landscape, then try to view the image uploaded from step 1.

Here is the original image: (Note the full red box)
<img src=https://github.com/FilenCloudDienste/filen-mobile/assets/3203214/8c6e06d1-0fd4-4961-9eee-da00de75db87 height=540 width=443>

And here is the same image viewed by the Filen app on iPad: (note that the top and bottom of the box are cut off.)
![IMG_1516](https://github.com/FilenCloudDienste/filen-mobile/assets/3203214/320580b7-148e-4185-8c29-98f026034e6a)

**Comment by Dwynr** [comment]
Thanks for reporting. Next update will include a new photo viewer which will fix this issue.
