### ISSUE TITLE
[Feature Request] Offline, Local Decryption for Files Made Available Offline

### ISSUE THREAD

**Issue by winb1g** [FilenCloudDienste/filen-mobile#284]
**Context**
For travelers, users who are on the subway or on airplanes, at times, we need to be able to access our files. We can't always perfectly plan out the files that we want to download or save to gallery before we lose access to the internet.
This becomes evermore prescient when dealing with the playback of larger files like Webinars, TV Shows, and Movies.

**Feature**
Allow users to decrypt the locally saved files, requiring auth methods like pin codes or biometrics.

**Comment by Dwynr** [comment]
You can already do that? Simply mark the files you want offline with "Make available offline".
