### ISSUE TITLE
There should also be an option to automatically sort the uploaded pictures into a sub-folder named after the Album they are associated to (on iOS, not sure how it works on Android). Right now in 2.0.44 you can already select separate Albums to synchronize, but then they all get thrown into the same folder.

### ISSUE THREAD

**Issue by HOBARTNOW** [FilenCloudDienste/filen-mobile#290]
There should also be an option to automatically sort the uploaded pictures into a sub-folder named after the Album they are associated to (on iOS, not sure how it works on Android). Right now in 2.0.44 you can already select separate Albums to synchronize, but then they all get thrown into the same folder.

_Originally posted by @skauertz in https://github.com/FilenCloudDienste/filen-mobile/issues/67#issuecomment-1474813115_

**Comment by Dwynr** [comment]
Added.

https://github.com/FilenCloudDienste/filen-mobile/pull/288/commits/f500ff441700ba85e7be098291c881aa02532fcd
