### ISSUE TITLE
Feature Request: Integrating of Filen into iOS to store files directly to Files and have Filen available in "Apple Files" (Dateien)

### ISSUE THREAD

**Issue by 21Kingshill** [FilenCloudDienste/filen-mobile#318]
Since Filen works reliable on MacOS and iOS / iPadOS it would be an important step to have a better integration into the mobile OS.
At the moment I do not see a way to store files from any application to Files directly which is a major drawback to me. 

Are there any plans (and rough dates) when this can be expected?

Thanks,
Tom

**Comment by Dwynr** [comment]
Already implemented, will ship in the next update in a few weeks.

**Comment by 21Kingshill** [comment]
Cool, thanks
