### ISSUE TITLE
2.70.0 RC1: app freezes after entering the folder with many items

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#327]
When I open the folder that contains more than a thousand files, the app freezes, even after the folder is opened and all files are loaded.

**Comment by Dwynr** [comment]
Not specific to the current RC release. Also present in earlier releases. We are still looking into ways to improve performance on really large folders. Fortunately this is only an issue for a really small amount of users who store thousands of files in a single folder. Easiest solution is to split up large directories right now.

**Comment by DanielProg39** [comment]
Got it. Just seems like the latest release version handles these much better. It could take some time to load the contents of the folder, but once loaded, I could search and upload files without any problems. However, in the RC, once the content has loaded, I can scroll through it, but other interface components (such as the search bar or buttons at the top) are unresponsive for a noticeable period of time.

**Comment by Dwynr** [comment]
Yea, we'll try to improve it.

**Comment by Dwynr** [comment]
This should improve it for now: https://github.com/FilenCloudDienste/filen-mobile/commit/5d6a5d46ac3074abdd9f9cc05188c400e8f4bb43
