### ISSUE TITLE
2.70.0 RC1: cannot upload multiple files at once

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#328]
I tried to upload two at once, but only one could be selected. If you need further clarification, I can make a screen recording that shows this problem.

**Comment by Dwynr** [comment]
I'd need a recording of some sort, not exactly sure what you mean.

**Comment by DanielProg39** [comment]
[Here it is](https://drive.filen.io/d/d1e01ebe-9a81-407d-840d-e048bc175289#nYarqVDeQbIzqVrh5o1HlilG6INqrP3B)

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-mobile/commit/aa0384a45021f31fb15f3919411b8ade9059d5b4
