### ISSUE TITLE
Text editor bug (2.70.0 RC1)

### ISSUE THREAD

**Issue by entropy1453** [FilenCloudDienste/filen-mobile#329]
Text can no longer be viewed in created/edited files
[Video](https://drive.filen.io/d/639bc6c4-c2fd-46e4-ab42-de0b0f7643dd#7e3lL2Co6riqVzSVCr9r0oIkM4kWWK9w)

**Comment by Dwynr** [comment]
I cannot directly reproduce this behaviour, but there will be a few extra changes in the next RC, this one might be fixed by then aswell. If not let me know.
