### ISSUE TITLE
2.70.0 RC1: SAF not accurate storage size

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#331]
It says I have more storage 'free' (15GB more to be exact) than I have total. Not a big deal, though, as the overall SAF integration has worked fine for me so far.

**Comment by Dwynr** [comment]
Android file managers usually use GB (Gigabyte) while our app uses GiB (Gibibytes).

For example: 200 GiB = 215 GB, therefore the displayed difference.

**Comment by DanielProg39** [comment]
Oh, that's great actually. Turns out I didn't know how much storage I had (turns out I have a lot more than I thought, lol). Maybe you should consider changing GB to GiB on the website and applications so people know what they're buying and aren't confused (as I was) about why their files take up less space in the cloud than locally 😉

**Comment by DanielProg39** [comment]
Oh, that's great actually. Turns out I didn't know how much storage I had (turns out I have a lot more than I thought, lol). Maybe you should consider changing GB to GiB on the website and applications so people know what they're buying and aren't confused (as I was) about why their files take up less space in the cloud than locally :)
