### ISSUE TITLE
Feature request: add 'Trash' to the top right button menu

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#332]
Here's what we have now:
![IMG_20240204_224244](https://github.com/FilenCloudDienste/filen-mobile/assets/63293432/a677bf30-316e-4de7-81d6-f12d95835376)

I think it would be more convenient to have Trash in this list so we don't have to open settings each time we need it. Is was OK in previous releases cause it still was two clicks away (settings > trash), now it's three clicks away (icon > settings > trash), which is less convenient.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-mobile/commit/fe57d4b5ec5fc6cf7827a1fd629f1748763459a8
