### ISSUE TITLE
2.70.0 RC1: Automatic background upload not working

### ISSUE THREAD

**Issue by zlatco** [FilenCloudDienste/filen-mobile#335]
Automatic background upload doesnt seem to work.
Is it not implemented yet?
How is it supposed to work, a watchdog, time based or triggered another way?

Device: Samsung S21 FE
Android 14  One UI 6.0

**Comment by Dwynr** [comment]
Background transfers are implemented.

If you are referring to the camera upload, then it depends on your device, android version, app usage patterns and other factors. Your device might put our app to sleep more frequently, or might never wake it up to perform background fetch tasks. Unfortunately we do not have any control over this (Ref: https://docs.expo.dev/versions/latest/sdk/background-fetch/). In the release version of the current beta we will begin sending periodic "silent" push notifications which might wake up your device and perform camera uploads.

**Comment by dobsinator** [comment]
Also, the synchronisation of deleted files doesn't work. After I've deleted a file on my Phone the file still remains in the cloud. Even after sync and upload...
