### ISSUE TITLE
2.0.70 (2070): Multiple files selection menu

### ISSUE THREAD

**Issue by flo-st** [FilenCloudDienste/filen-mobile#339]
If multiple files are selected in landscape mode and then the file selection menu is opened, it is not possible to move files into the recycle bin.
Even if the device is rotated, the selection options disappear at the bottom and cannot be seen or scrolled down.

It would also be helpful if the options were visible in the file selection menu when only one file is selected, rather than opening a different menu for each file, to improve usability.

The German translation is also a little confusing. There are two "Papierkorb" options. One to move files to the recycle bin and another to open the recycle bin.

**Comment by Dwynr** [comment]
There is simply not enough screen height to display all action sheet options in ladnscape mode - something we need to address in a later update.

I agree with the double "trash" option - We'll fix that.
