### ISSUE TITLE
Feature request - Search via Spotlight

### ISSUE THREAD

**Issue by Eseltwift** [FilenCloudDienste/filen-mobile#341]
Would it be possible to search for any Filen Drive item directly from Spotlight search on iOS?

I usually search for documents on the fly this way. For example I need to find an old invoice, I just start typing "invoice" in Spotlight search and it shows me the corresponding items in my Drive. I thought this feature would come with the recent compatibility with the Files app.

**Comment by Dwynr** [comment]
We have no control over the internal iOS Spotlight search, and iirc there is no way to explicitly tell iOS to include our File Provider in the spotlight search, unfortunatey.
