### ISSUE TITLE
Cannot open files in iOS files provider integration 

### ISSUE THREAD

**Issue by szapp** [FilenCloudDienste/filen-mobile#346]
With the new update 2.0.70 (on iOS 16.7.5), I am now able to upload files through the iOS files app and see all the filen files there. However, I cannot access any of the listed files. When attempting to open a file, I receive an error box with the title "The file doesn't exist." with the same note underneath "The file doesn't exist."

Regardless whether the file is made available offline from the filen app, this error seems to always occur rendering the iOS files provider integration quite limited at this time.

Is there some setting I am missing?

**Comment by Dwynr** [comment]
Try cold restarting your device. iOS might not have picked up the files provider correctly when the app was updated.

**Comment by szapp** [comment]
Thanks for the quick reply!

I tried a hard/cold reset, re-installing the filen app, retrying with its default settings, deleting the iCloud backup of its settings - repeatedly and and in different order to no avail.

Unfortunately, the error persists and the files provider integration does not work for me.

I might help to hear from other users if it works or does not for them, especially with the same iOS version. I will ask around on the discord server.

**Comment by szapp** [comment]
It seems that it might be related to the iOS version as discussed on Discord:

> Im still on ios 16.7.3 with that phone and yes can confirm, "files dont exist". On the other site, ios 17.4 beta works completely fine

Source: https://discord.com/channels/724449174334078996/724450102944464896/1208429692374351872

**Comment by Dwynr** [comment]
I can reproduce it in an iOS simulator running 16.4. Will look into fixing it.

**Comment by Dwynr** [comment]
Fixed, thanks to @lingfeishengtian 

Ref: https://github.com/FilenCloudDienste/filen-mobile/pull/349
