### ISSUE TITLE
PlayStore's 2.0.70 incorrect menu options

### ISSUE THREAD

**Issue by m0yP** [FilenCloudDienste/filen-mobile#353]
When selecting multiple files and open context menu, got Trash two times. 

One is to actually remove the selected files and the other one takes you to the Trash folder.

![Screenshot_20240224-160429](https://github.com/FilenCloudDienste/filen-mobile/assets/22119314/e5da8be3-886e-48a2-aa08-82259f51731f)

**Comment by Dwynr** [comment]
Already fixed, included in the update scheduled for next week.
