### ISSUE TITLE
Filen app on iOS freezes when opening a folder with a lot of files.

### ISSUE THREAD

**Issue by jsvdmeer** [FilenCloudDienste/filen-mobile#356]
Hi,

After the latest update I decided to upload my whole camera roll to my Filen drive. 
I now have a folder with over 20.000 photos. Whenever I try to open this folder, the Filen app completely freezes and I have to restart the app in order to use it again.

With the Filen WebApp loading the same folder also takes a very long time. It doesn't freeze however.

Is this a known issue? And is a fix for this problem coming soon?

Best regards!

**Comment by skarvall** [comment]
Version 2.0.72 • was relseasd earlier today, did it fix your issue?

- **Improved performance when loading really large folders**
- Better image component
- Added a proper splashscreen
- Added hungarian translation
- General bug fixes

**Comment by skarvall** [comment]
> Hi,
> 
> After the latest update I decided to upload my whole camera roll to my Filen drive. I now have a folder with over 20.000 photos. Whenever I try to open this folder, the Filen app completely freezes and I have to restart the app in order to use it again.
> 
> With the Filen WebApp loading the same folder also takes a very long time. It doesn't freeze however.
> 
> Is this a known issue? And is a fix for this problem coming soon?
> 
> Best regards!

Version 2.0.72 • was relseasd earlier today, did it fix your issue?

- **Improved performance when loading really large folders**
- Better image component
- Added a proper splashscreen
- Added hungarian translation
- General bug fixes

**Comment by jsvdmeer** [comment]
Yeah, that fixed it. Awesome!
Thanks!
