### ISSUE TITLE
Restoring files from trash doesn't work

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#36]
When I accidentally deleted a file (picture), I opened Trash and tapped Restore. This made a file disappear from a trash folder but it didn't appear in the previous destination after that. Refreshing doesn't help

**Comment by Dwynr** [comment]
Yea looks like the internal app cache is not properly updating. The item remains restored if you check it on our website for example. Will fix in the next release.

**Comment by DanielProg39** [comment]
@Dwynr I noticed that this happens only if you delete a file using mobile app. If you delete file from the browser and then restore it from mobile, it would appear in the restore destination in mobile application

**Comment by Dwynr** [comment]
Fixed in the next update.
