### ISSUE TITLE
Can't download any files

### ISSUE THREAD

**Issue by iammeline** [FilenCloudDienste/filen-mobile#37]
When I try to download any file the following text box appears:

![20220415_194951](https://user-images.githubusercontent.com/82101902/163650798-d768a802-7b67-4692-98ba-d9a8e89fa49f.jpg)

App version: 2.0.12
Using Android 10

**Comment by Dwynr** [comment]
This means the app could not instantiate a write stream. Did you give the app complete storage permissions?

**Comment by iammeline** [comment]
Do you mean under "App permissions" in the settings? Yes.

![20220417_214921](https://user-images.githubusercontent.com/82101902/163738955-81a756d4-7dec-4bdd-947b-9e51505f5234.jpg)

**Comment by Dwynr** [comment]
Should be fixed in the next update.
