### ISSUE TITLE
How to auto-upload files and documents other than photos and videos? 

### ISSUE THREAD

**Issue by pixincreate** [FilenCloudDienste/filen-mobile#38]
Is that even possible or have to be done manually? I couldn't find an option to upload documents and other stuffs automatically..

Or if the app doesn't have that feature, will it be implemented in the coming days?

As for reference, you can checkout nextcloud where the user can auto upload the files in a same format of the user's DIR on the phone by means of customisation. 

Also, uploading `Camera Upload` needs a small rework IMO as I believe, it is unreliable. Meaning, enabling that option uploads every photo and video from every directory into a single folder instead of uploading to respective folders atleast by creating them automatically which messes up the purpose of that auto-upload option.

**Comment by Dwynr** [comment]
Currently not possible, but we will definitely take it into consideration in the future.

As for more options for the camera upload: Working on it.

**Comment by pixincreate** [comment]
> Currently not possible

Any reason for rejection as of now? So, we've to rely upon manual upload itself as of now...

> As for more options for the camera upload: Working on it.

Thank you for acknowledgement. Hope you add directory during uploading of images and videos.

Example:      
Instead of uploading `image.jpg`, we can make something like `storage\DCIM\Camera\image.jpg` where `storage`, `DCIM` and `Camera` are directories and are auto created during upload.

**Comment by jnolan7599** [comment]
> Also, uploading Camera Upload needs a small rework IMO as I believe, it is unreliable. Meaning, enabling that option uploads every photo and video _**from every directory**_ into a single folder instead of uploading to respective folders atleast by creating them automatically which messes up the purpose of that auto-upload option. ( &mdash; @pixincreate, emphasis mine)

Seconded. I waste too much time undoing what I though I mis-configured only to find out it doesn't seem possible to set a custom path. I don't need a music collection's album art &/or OEM wallpapers uploaded.

See [Feature Request] User configurable photos dir (eg: SD card, USB-OTG) #143

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
