### ISSUE TITLE
Folders cannot be uploaded

### ISSUE THREAD

**Issue by pixincreate** [FilenCloudDienste/filen-mobile#39]
![Screenshot_20220416-095551_Filen](https://user-images.githubusercontent.com/69745008/163661310-71d4fec5-a887-4db1-ac2f-d04ae21fa150.png)

I tried to upload `documents dir` directly through `share menu` into the filen_io and got the error shown in the screenshot above.

**Comment by Dwynr** [comment]
Will look into it.

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
