### ISSUE TITLE
[Improvement] Add French language to the app

### ISSUE THREAD

**Issue by DodoLeDev** [FilenCloudDienste/filen-mobile#40]
**Hi everyone!**
### I'm glad to announce that I've completed the translation of the app into French!

I've linked the [`fr.js`](https://github.com/FilenCloudDienste/filen-mobile/files/8500073/fr.js.txt) file to this issue, which goes into the `filen-mobile/src/i18n/lang/` folder.
<br>
<br>
<br>

---
And finally, last comment: *This service is incredible! I love it! Keep it up, guys!* 💪

**Comment by Dwynr** [comment]
Merged! Thank you :)
