### ISSUE TITLE
Comparing the app with pCloud (personal experience)

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#44]
Hi. I have found a promocode for 500Gb storage for three month in pCloud, so I decided to try it out.
_However, I still prioritize Filen due to end-to-end encryption by default, great privacy policy, FOSS app and generous rewards for inviting others. So I'll delete my pCloud account when this three-month promotion will expire._
In the first place, I wanted to compare look and feel of Filen and pCloud apps. And I want to share my thoughts with you.
Firstly, a Filen app has nicer and fresher look and feels more minimalistic and comfortable. The Photo tab is situated more conveniently then the similar thing is implemented in pCloud. Also, Filen has more useful settings, especially when it comes to account settings.
On the other hand, what I like very much about pCloud is an in-app preview. You can watch videos while they are loading, view and zoom pictures and documents. It even has the built-in music player, where you can listen to music and make playlists. Another must-have feature that must be implemented in Filen is a notification that shows the uploading/downloading status. I hope that one day these features would be implemented in Filen.
Well, that's all for now. Have a nice day 😉

**Comment by Dwynr** [comment]
Hi,

the new app is far from being polished -  There's still a lot on the to-do list and everything you've mentioned will be improved.

**Comment by DanielProg39** [comment]
I deleted my pCloud account. Reason? I read their privacy policy and looked up their privacy score in TOS:DR and Osano privacy meter. "Privacy oriented" Swiss company gives up your data to advertisement companies to personalise ads and gathers huge amount of "anonymised or pseudonymised" analytics. And take a look at their website:
![Screenshot_2022-04-25-17-27-56-448_com brave browser](https://user-images.githubusercontent.com/63293432/165110064-e91de1a9-97c2-475f-a4e0-3ea59823821c.jpg)
My Firefox also warned me that by typing email in the register form on main page I, in fact, give it up to Facebook.
So I decided that I woudn't get back to this sh*t.
The moral of the story: do not trust beautiful words in the main page of any website. Dig deeper to find the real information. The best way to do that - read privacy policy and terms of each service.

**Sorry, I know that this comment is off-topic but I wrote it with hope that it will help someone**

**Comment by DodoLeDev** [comment]
> The best way to do that - read privacy policy and terms of each service.

@DanielProg39

Good news! I'm also contributing to an open source service which does this laborious task for you:
### ✨ [Terms Of Service; Didn't Read](tosdr.org) ✨
~~If you have some days to spare,~~ feel free to contribute to this amazing project!

**Comment by DanielProg39** [comment]
@DodoLeDev I know about this service and use it time to time. I also mentioned it in the issue description:

> I read their privacy policy and looked up their privacy score in **TOS;DR** and Osano privacy monitor.

It is an awesome service and I'll think about contributing to it (good idea, strangely, but never came up with it before 🤔)
