### ISSUE TITLE
Pictures not scrollable on android

### ISSUE THREAD

**Issue by duergrim** [FilenCloudDienste/filen-mobile#54]
When trying to open a picture on android, it asks me which app I want to open the app with. When I, for example choose my gallery app, it seems the pictures aren't scrollable (not able to scroll through pictures) either.

https://imgur.com/a/U70YJXS

**Comment by duergrim** [comment]
![IMG_20220420_222642.jpg](https://user-images.githubusercontent.com/44030905/164552784-7e68bddb-4859-4341-9f62-eeff4ce478aa.jpg)

@Dwynr

**Comment by Dwynr** [comment]
Added in the new update.
