### ISSUE TITLE
Error on upload. Error: socket hang up.

### ISSUE THREAD

**Issue by EmirLogas** [FilenCloudDienste/filen-mobile#58]
When I start upload files, giving error after 1, 2 second. Error: socket hang up.

![Screenshot_20220423-174018_Filen](https://user-images.githubusercontent.com/76751818/164910816-0603e0e7-3ef0-4a95-a190-967f3b8724b0.jpg)

**Comment by DanielProg39** [comment]
Strange, I don't experience this issue
