### ISSUE TITLE
An Error (an app doesn't receive an actual file, marking it as undefined)

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#59]
Got this error when trying to upload a video by sending it from Telegram. When downloaded to a device and uploaded to cloud using the app, everything works fine. Earlier I've uploaded a file from my local storage using sharing option and there were no errors.
![IMG_20220424_220042](https://user-images.githubusercontent.com/63293432/164992219-9dd7cd3e-807e-4f09-a4af-36b564fb25b8.jpg)
![IMG_20220424_214927](https://user-images.githubusercontent.com/63293432/164991831-2884706e-1502-4728-8aa7-0ff6ed78e8db.jpg)

**Comment by Dwynr** [comment]
Will check what's wrong.

**Comment by DanielProg39** [comment]
The file size is about 98MB. In case it helps

**Comment by Dwynr** [comment]
Should be fixed now.
