### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by duergrim** [FilenCloudDienste/filen-mobile#6]
http://imgur.com/a/3aAsLCl renaming doesn't show full folder name

http://imgur.com/a/CPnG077 bug when typing. the app deletes some random letters.

http://imgur.com/a/P92k9fj sorting bug.

http://imgur.com/a/GEc7wdp i don't know whether this is a bug or a missing feature, but when opening a folder you've searched for, and going back, it doesn't go back to the search results, it goes all the way back.

**Comment by duergrim** [comment]
@Dwynr please fix this bugs in the next version

**Comment by Dwynr** [comment]
1 fixed
2 fixed
3 not a bug, just how programatic sorting works in js
4 missing feature, will be added in the future
