### ISSUE TITLE
A very minor issue, but still worth looking

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#61]
When I rename a folder, create a new one or delete a file and then relaunch the app, I see this error:
![Screenshot_2022-05-02-01-00-54-963_io filen app](https://user-images.githubusercontent.com/63293432/166166852-6619d383-4ddf-4df0-afa4-ff69de478ba9.jpg)
Everything works fine. However, after renaming the folder, if I open it without restarting the app, it will still show its old name in the title bar. This can be fixed only by restarting the app

**Comment by Dwynr** [comment]
Fixed in the next update.
