### ISSUE TITLE
Edit: An issue caused by me, don't pay attention

### ISSUE THREAD

**Issue by DanielProg39** [FilenCloudDienste/filen-mobile#63]
Got this multiple times when was syncing photos and videos
![Screenshot_2022-05-04-00-24-05-404_io filen app](https://user-images.githubusercontent.com/63293432/166571015-9ecbdd26-6588-405d-bb48-0976486c9c48.jpg)

**Comment by DanielProg39** [comment]
Got this error two times when I was uploading only two photos

**Comment by DanielProg39** [comment]
I took a small investigation and found out that this is AdGuard slowing down connection. So it's my fault 😄

**Comment by Dwynr** [comment]
Okay thanks for further investigating. I will probably add a higher timeout to the connection so it still goes through instead of timing out when the user has a slow connection.
