### ISSUE TITLE
German not available?

### ISSUE THREAD

**Issue by Kugane** [FilenCloudDienste/filen-mobile#78]
I have noticed that one German is not available in the selection 
![Screenshot_20220702_174732_io.filen.app.jpg](https://user-images.githubusercontent.com/14034601/177007396-ca69db22-2e82-457b-9848-5a7fc7513d25.jpg)

**Comment by Dwynr** [comment]
A german translation will be included in the next update.

Rel: https://github.com/FilenCloudDienste/filen-mobile/commit/64a534737e143f0e60a939803ca72c441529cfbe
