### ISSUE TITLE
German translation not working

### ISSUE THREAD

**Issue by MalteKiefer** [FilenCloudDienste/filen-mobile#80]
Good day,

I have installed filen on my computer.
I have a OnePlus 9 Pro with Android 12.

Unfortunately, the German language is not displayed as an option.
However, here in the source I see that the app is translated into German:

![Screenshot_2022-07-10-21-12-10-09_a46b00b63903fd95f2c92a824c05ddce](https://user-images.githubusercontent.com/59220985/178158760-6823454a-95e6-4754-826e-b62173fa71ee.jpg)

**Comment by Dwynr** [comment]
German is implemented but we did not publish the latest updates to the App Stores yet. It will be included once we release the update.

**Comment by MalteKiefer** [comment]
Is there a time frame for it?
