### ISSUE TITLE
[Feature Request] Restrict images based on local folders for camera upload

### ISSUE THREAD

**Issue by sarekv** [FilenCloudDienste/filen-mobile#83]
Firstly, thanks for this great app.

Currently camera uploads just seem to scan all image files on the device and upload them. I cannot find any setting or way to prevent for example whatsapp or telegram downloaded images from getting uploaded into the filen cloud. 

This causes unnecessary data usage and battery drain. An option to only restrict the images in scope for upload to a specific folder would solve this (example the DCIM folder only).

**Comment by Dwynr** [comment]
This will be included in the next release. Already implemented into the codebase.
