### ISSUE TITLE
Integration with iOS Files App

### ISSUE THREAD

**Issue by ashutoshsaboo** [FilenCloudDienste/filen-mobile#85]
Hi, an integration with the files app on ios would be super awesome, like gdrive does. Would make it super convenient for accessing files too, additionally this will add the support for all kinds of ios shortcuts for Filen (even though not natively, but for free) - for ex: based on some condition copy a folder from another directory in files app to filen dir in files app & then filen app would take care of auto uploading/syncing the new file that was pasted. One usecase can be for some sort of backups on device or anything else.

This would be really great to have! Can this be please considered soon for the ios mobile app?

**Comment by dermitdemdino** [comment]
This would be absolute top. And also the shared folders should be visible there.

**Comment by naheller** [comment]
+1 to this request!

**Comment by marcoclg19** [comment]
This feature would be extremely useful... when will it be available?

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
