### ISSUE TITLE
[Feature Request] Storage Access Framework (SAF)

### ISSUE THREAD

**Issue by 3504k** [FilenCloudDienste/filen-mobile#9]
It appears that the Android app doesn’t have SAF permissions. I notice when trying to open a Keepass file, all other cloud providers are shown except Filen.

Thanks for your work and help.

**Comment by julianfairfax** [comment]
This would definitely be nice!

**Comment by EdwardLangdon** [comment]
Any Updates on this. Mr @Dwynr

**Comment by Pijunoid** [comment]
Yes I'd like this to be implemented so I can use Joplin accross my devices

**Comment by jnolan7599** [comment]
I'm adding another vote here. Had there been any updates since Oct 2021? I'm not seeing anything mentioned in the release changelogs.

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
