### ISSUE TITLE
Ability to upload folders straight into the app, as well as via Share option

### ISSUE THREAD

**Issue by ashutoshsaboo** [FilenCloudDienste/filen-mobile#91]
Ability to Allow selecting folders in file manager for upload, and Filen should automatically create directory structure and upload relevant files. If there are nested folders/files so should be created by Filen as well, i.e, the directory structure must be preserved as is. 

Also there should be an option in the share button to select folders and queue them for upload on Filen.

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
