### ISSUE TITLE
Bug: Why is the max file share limit for uploading files to Filen set to 10??

### ISSUE THREAD

**Issue by ashutoshsaboo** [FilenCloudDienste/filen-mobile#92]
Looks like when you select more than 10 files and share them to Filen for upload, Filen gives an error that total files shared must be less than 10. This seems to be bad UX for uploading folders containing large number of files. Please remove this limitation for the mobile apps. Not sure if this is a constraint for desktop/web apps too, haven't tested yet.

**Comment by Dwynr** [comment]
Not a bug, just a soft limit. Raised it to 100 for the next update.

https://github.com/FilenCloudDienste/filen-mobile/commit/b7b577b24497c2405c541aecf44fdb68cb23b06f#diff-753d47d5a4a5b2a6b46382e912325dac57a6e736ebc1382b1b85242197f53f0dR667
