### ISSUE TITLE
Ability to mark folders for offline usage rather than just files (as in the current state)

### ISSUE THREAD

**Issue by ashutoshsaboo** [FilenCloudDienste/filen-mobile#93]
Ability to mark folders for offline usage rather than just files - let's say if I mark a folder for offline usage and later add more files to the same folder from another client (web/desktop), then it'd be beneficial to have the file auto downloaded (once the mobile app syncs) for offline usage as well, since the parent folder was marked for offline usage. If there are nested folders inside the parent folder that I marked for offline usage, then same behaviour can apply to them as well - i.e, if any new files are downloaded to a child folder under a parent folder which was marked for offline usage, then they should also be downloaded to the device once it sync for offline usage. 

Common usecase: As a user, I would like to have a folder of personal IDs/docs always available and synced with my device for offline usage. I can always keep on adding more relevant files to it in future, and they should auto sync with my local device for offline usage as well. Otherwise, it's painful in the current state to go mark each file for offline access manually whenever a new file is uploaded from another client (desktop/web).

**Comment by jnolan7599** [comment]
+1 here.

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150

**Comment by ashutoshsaboo** [comment]
Sorry how's this related to storage access framework integration? To the best of my knowledge (and i might be wrong, so feel free to correct), Cryptomator already supports SAF but doesn't have this support. Filen already has this support for marking files for offline usage, just needs to add capability to auto download files when triggered (that trigger can happen during app startup or whenever) in a certain folder marked for offline usage. I might be wrong, but to me this looks like either a separate request or at best a request on top of SAF (depending on how you plan to implement this, as that'd decide how you look at this). 

To be clear I'm not mentioning about syncing a local folder with Filen mobile app here, but rather downloading it for offline usage. Both are different things. Latter allows for usecases like I upload a set of personal docs from my laptop (as it's easier to upload from laptop) in a folder on Filen, but given it's marked as offline usage on my mobile app it would be still be accessible offline. So if I want to show my personal docs to anyone, then all of the files in the folder should be available offline automatically whenever a new one is uploaded. 

With this context^, don't you think the related issue that you marked and this are different? If yes, could you re-open this issue? @Dwynr
