### ISSUE TITLE
[Feature Request] (Read below for more details) The app doesn't show up in DocumentsUI (No SAF) as a cloud storage provider and *5 ISSUES*

### ISSUE THREAD

**Issue by pixincreate** [FilenCloudDienste/filen-mobile#94]
The title says it all. Let me dig in for more details.  

### Before I start digging, let me give a quick critique (issues)
- [ ] The current app version is buggy and doesn't seem to be useful for **daily** use. I'm not sure if it is fixed in the upcoming update or not.    
- [ ] The dev doesn't seem to commit after every single update but after changing a lot of files. This IMO makes debugging and reverting updates harder.
- [ ] The app upload speed is slow and often stops uploading, app itself is slow and sluggish and doesn't feel like a native app in any way and also it encourages me to not open that app.
- [ ] I recommend using `firebase` / `appwrite (open source implementation of firebase)` for faster development. And I'm unsure if that is compatible with typescript. Publish app updates in **Beta** channel (on Google Play).
- [ ] You can look at [this](https://blog.zhanghai.me/writing-a-comparator-for-natural-sort-order/) this blog for sorting the files.
  - [ ] As of now, I can see the files being sorted in an order of `1, 11, 12, 113, 2, 21, 22, 234, 5, 51, 52, 6` instead of `1, 2, 5, 6, 11, 12, 21, 22, 51, 52, 113, 234`
- [ ] This app doesn't even open if the internet is turned-off! And the app itself is **extremely slow** to load even when the internet is turned-on (takes nearly 20secs for me)

### Coming back to the topic:
- Presently, almost every cloud provider has an app and other applications like a `files app` tends to recognize it which I believe is not by name but rather a file within the the `cloud app`. By this, all I can say is that the filen.io app on Android (as well as iOS) doesn't support or have native Android/iOS support.
  - This really hinders the usability accessibility of seamless transfer of files
- What I mean by this is shown in the image below:
![Screenshot_20220814-170955_Files](https://user-images.githubusercontent.com/69745008/184535088-b5e80794-cc2c-45d7-81e8-7ebba677440e.png)
- If you see the image, GDrive and the ProtonDrive are shown up in the `Documents UI app`. 
- Also, if you create a new folder within the `Documents UI`, a new folder will be created in the cloud app when it is connected to the internet. 
- This doesn't and cannot be done with Filen_io as of now. And it doesn't feel like a native app.

**Comment by igorer88** [comment]
@pixincreate I would suggest that you open issues for individual or groups of problems you encounter, so it helps them to organize better in order to solve them.

**Comment by jnolan7599** [comment]
+1

**Comment by Dwynr** [comment]
Rel: https://github.com/FilenCloudDienste/filen-mobile/issues/150
