### ISSUE TITLE
[Feature Request]: Heic image/thumbnail preview for Android.

### ISSUE THREAD

**Issue by actuallyaryaman** [FilenCloudDienste/filen-mobile#98]
The .heic format is merely doesn't open on the android app as of now with is quite a bummer. If the android app and the web browser would have the capability just like it's iOS counterpart it would be amazing.

**Comment by Dwynr** [comment]
https://github.com/FilenCloudDienste/filen-mobile/commit/6b79507670a15cbc0d99530b8fbf39cdcc50965f

**Comment by actuallyaryaman** [comment]
I can't understand why this issue is marked as closed, since this bug/feature has not been implemented properly. Thank you.
